used "two spaces" identation, improved code

diff --git a/src/gen-ssl-kurenma b/src/gen-ssl-kurenma
--- a/src/gen-ssl-kurenma
+++ b/src/gen-ssl-kurenma
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id: gen-ssl-kurenma 111 2016-10-18 17:32:07+04:00 toor $
+# $Id: gen-ssl-kurenma 134 2017-02-02 22:24:38+04:00 toor $
 #
 _bashlyk=kurenma . bashlyk
 #
@@ -35,132 +35,132 @@ _bashlyk=kurenma . bashlyk
 #******
 udfMain() {
 
-	udfExitIfAlreadyStarted
+  udfExitIfAlreadyStarted
 
-	[[ $UID == 0 ]] || eval $( udfOnError throw NotPermitted "You must be root to run this." )
+  [[ $UID == 0 ]] || eval $( udfOnError throw NotPermitted "You must be root to run this." )
 
-	udfThrowOnCommandNotFound chmod cp date echo mkdir openssl rm sed tee touch wg
+  udfThrowOnCommandNotFound chmod cp date echo mkdir openssl rm sed tee touch wg
 
-	local conf confDN csv fnTemplate path pathCnf pathCrt pathCsr pathIni pathKey s
+  local conf confDN csv fnTemplate path pathCnf pathCrt pathCsr pathIni pathKey s
 
-	pathIni=$( _ pathIni )
-	udfThrowOnEmptyVariable pathIni
+  pathIni=$( _ pathIni )
+  udfThrowOnEmptyVariable pathIni
 
-	path=${pathIni}/ssl
-	pathCsr=${path}/csr
-	pathCrt=${path}/public
-	pathCnf=${path}/configs
-	pathKey=${path}/private
-	confDN=${pathIni}/dn.kurenma.ini
-	fnTemplate=/usr/share/kurenma/openssl.cnf.template
-	csv='C;ST;L;O;OU;CN;EA'
+  path=${pathIni}/ssl
+  pathCsr=${path}/csr
+  pathCrt=${path}/public
+  pathCnf=${path}/configs
+  pathKey=${path}/private
+  confDN=${pathIni}/dn.kurenma.ini
+  fnTemplate=/usr/share/kurenma/openssl.cnf.template
+  csv='C;ST;L;O;OU;CN;EA'
 
-	eval $( udfLocalVarFromCSV $csv )
+  eval $( udfLocalVarFromCSV $csv )
 
-	udfIni $confDN ":${csv}"
+  udfIni $confDN ":${csv}"
 
-	: ${C:=XX}
-	: ${ST:=State}
-	: ${L:=Locality}
-	: ${O:=Organizational}
-	: ${OU:=OrganizationalUnit}
-	: ${CN:=CommonName}
+  : ${C:=XX}
+  : ${ST:=State}
+  : ${L:=Locality}
+  : ${O:=Organizational}
+  : ${OU:=OrganizationalUnit}
+  : ${CN:=CommonName}
 
-	for s in "$confDN" "$fnTemplate"; do
+  for s in "$confDN" "$fnTemplate"; do
 
-		[[ -f $s ]] || eval $( udfOnError throw NoSuchFileOrDir "$s" )
+    [[ -f $s ]] || eval $( udfOnError throw NoSuchFileOrDir "$s" )
 
-	done
+  done
 
-	eval set -- $( _ sArg )
+  eval set -- $( _ sArg )
 
-	case "$1" in
+  case "$1" in
 
-	 ca)
+   ca)
 
-		if [[ -s ${pathKey}/cakey.pem && -s ${pathCrt}/cacert.pem ]]; then
+    if [[ -s ${pathKey}/cakey.pem && -s ${pathCrt}/cacert.pem ]]; then
 
-			eval $( udfOnError exitecho Unexpected "Already exist ${pathKey}/cakey.pem and/or ${pathCrt}/cacert.pem" )
+      eval $( udfOnError exitecho Unexpected "Already exist ${pathKey}/cakey.pem and/or ${pathCrt}/cacert.pem" )
 
-		fi
+    fi
 
-	 	mkdir -p ${path}/{public,private,configs,certs,newcerts,crl,csr}
-		chmod 0710 $pathKey
+     mkdir -p ${path}/{public,private,configs,certs,newcerts,crl,csr}
+    chmod 0710 $pathKey
 
-		date "+%s" > ${path}/serial
-		date "+%s" > ${path}/crlnumber
+    date "+%s" > ${path}/serial
+    date "+%s" > ${path}/crlnumber
 
-		rm -f ${path}/index.txt
-		touch ${path}/index.txt
+    rm -f ${path}/index.txt
+    touch ${path}/index.txt
 
-		conf=${pathCnf}/kurenma.ssl
+    conf=${pathCnf}/kurenma.ssl
 
-		: ${EA:=email@domain.name}
+    : ${EA:=email@domain.name}
 
-		;;
+    ;;
 
-	 client|server)
+   client|server)
 
-		[[ -n "$2" ]] || eval $( udfOnError exitecho EmptyOrMissingArgument "argument required.. see usage" )
+    [[ -n "$2" ]] || eval $( udfOnError exitecho EmptyOrMissingArgument "argument required.. see usage" )
 
-		if [[ -s ${pathKey}/${2}.key && -s ${pathCrt}/${2}.crt ]]; then
+    if [[ -s ${pathKey}/${2}.key && -s ${pathCrt}/${2}.crt ]]; then
 
-			eval $( udfOnError exitecho Unexpected "Already exist ${pathKey}/${2}.key and/or ${pathCrt}/${2}.crt" )
+      eval $( udfOnError exitecho Unexpected "Already exist ${pathKey}/${2}.key and/or ${pathCrt}/${2}.crt" )
 
-		fi
+    fi
 
-		for s in "$path" "$pathKey" "$pathCrt" "$pathCsr" "$pathCnf"; do
+    for s in "$path" "$pathKey" "$pathCrt" "$pathCsr" "$pathCnf"; do
 
-			[[ -d "$s" ]] || eval $( udfOnError throw NoSuchFileOrDir "$s" )
+      [[ -d "$s" ]] || eval $( udfOnError throw NoSuchFileOrDir "$s" )
 
-		done
+    done
 
-		conf=${pathCnf}/${2}.kurenma.ssl
+    conf=${pathCnf}/${2}.kurenma.ssl
 
-		: ${EA:=postmaster@$2}
+    : ${EA:=postmaster@$2}
 
-		OU=${2%%.*}
-		CN=$2
+    OU=${2%%.*}
+    CN=$2
 
-		;;
+    ;;
 
-	 *)
+   *)
 
-		echo "Error: unknown option.. ${*}"
-		echo "usage: ${0##*/} ca | { client|server <CommonName> }"
-		exit 1
+    echo "Error: unknown option.. ${*}"
+    echo "usage: ${0##*/} ca | { client|server <CommonName> }"
+    exit 1
 
-	esac
+  esac
 
-	cp $fnTemplate $conf || eval $( udfOnError throw NoSuchFileOrDir $conf )
+  cp $fnTemplate $conf || eval $( udfOnError throw NoSuchFileOrDir $conf )
 
-	for s in ${csv//[;,]/ }; do
+  for s in ${csv//[;,]/ }; do
 
-		sed -i -r -e "s/%${s}%/${!s}/ig" $conf
+    sed -i -r -e "s/%${s}%/${!s}/ig" $conf
 
-	done
+  done
 
-	case "$1" in
+  case "$1" in
 
-	 ca)
-		openssl req -nodes -new -x509 -keyout ${pathKey}/cakey.pem -out ${pathCrt}/cacert.pem -days 3650 -config $conf -verbose
+   ca)
+    openssl req -nodes -new -x509 -keyout ${pathKey}/cakey.pem -out ${pathCrt}/cacert.pem -days 3650 -config $conf -verbose
 
-		;;
+    ;;
 
-	 client|server)
+   client|server)
 
-		sed -i -r -e "s/%nsCertType%/${1}/ig" $conf
+    sed -i -r -e "s/%nsCertType%/${1}/ig" $conf
 
-		[[ "$1" == "server" ]] && openssl dhparam -out ${pathCrt}/dh2048.pem 2048
+    [[ "$1" == "server" ]] && openssl dhparam -out ${pathCrt}/dh2048.pem 2048
 
-		openssl req -new -nodes -keyout ${pathKey}/${2}.key -out ${pathCsr}/${2}.csr -config $conf -verbose
-		openssl ca  -in ${pathCsr}/${2}.csr -out ${pathCrt}/${2}.crt -config $conf -verbose
+    openssl req -new -nodes -keyout ${pathKey}/${2}.key -out ${pathCsr}/${2}.csr -config $conf -verbose
+    openssl ca  -in ${pathCsr}/${2}.csr -out ${pathCrt}/${2}.crt -config $conf -verbose
 
-		;;
+    ;;
 
-	esac
+  esac
 
-	chmod 0600 ${pathKey}/*
+  chmod 0600 ${pathKey}/*
 
 }
 #
diff --git a/src/update-firehol b/src/update-firehol
--- a/src/update-firehol
+++ b/src/update-firehol
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #
-# $Id: update-firehol 106 2016-10-14 13:56:06+04:00 toor $
+# $Id: update-firehol 134 2017-02-02 22:24:39+04:00 toor $
 #
 #
 _bashlyk=kurenma . bashlyk
@@ -38,131 +38,131 @@ _bashlyk_hError[$_bashlyk_iErrorTimeExpired]="time expired"
 #******
 udfMain() {
 
-	udfExitIfAlreadyStarted
+  udfExitIfAlreadyStarted
 
-	[[ $UID == 0 ]] || eval $( udfOnError throw iErrorNotPermitted "You must be root to run this." )
+  [[ $UID == 0 ]] || eval $( udfOnError throw iErrorNotPermitted "You must be root to run this." )
 
-	udfThrowOnCommandNotFound cp date diff echo firehol flock grep kurenmactl mkdir mv rm sed sort touch uniq wg xargs
+  udfThrowOnCommandNotFound cp date diff echo firehol flock grep kurenmactl mkdir mv rm sed sort touch uniq wg xargs
 
-	local cnf csv fn fnKnock fnLock ini ipv4Black ipv4Client ipv4White pathDat pathIni s sDig
+  local cnf csv fn fnKnock fnLock ini ipv4Black ipv4Client ipv4White pathDat pathIni s sDig
 
-	pathDat=$( _ pathDat )
-	fnKnock="${pathDat}/lastknocks.dat"
-	fnLock="$( _ pathRun )/$( _ s0 ).lock"
-	mkdir -p $pathDat || eval $( udfOnError throw NotExistAndNotCreated $pathDat )
-	touch $fnLock || eval $( udfOnError throw NotExistAndNotCreated $fnLock )
+  pathDat=$( _ pathDat )
+  fnKnock="${pathDat}/lastknocks.dat"
+  fnLock="$( _ pathRun )/$( _ s0 ).lock"
+  mkdir -p $pathDat || eval $( udfOnError throw NotExistAndNotCreated $pathDat )
+  touch $fnLock || eval $( udfOnError throw NotExistAndNotCreated $fnLock )
 
-	eval set -- $( _ sArg )
+  eval set -- $( _ sArg )
 
-	s=$( udfGetValidIPsOnly $1 ) || eval $( udfOnError exitecho InvalidArgument "IP or hostname required" )
+  s=$( udfGetValidIPsOnly $1 ) || eval $( udfOnError exitecho InvalidArgument "IP or hostname required" )
 
-	if [[ -z "$_kurenma_flock" ]]; then
+  if [[ -z "$_kurenma_flock" ]]; then
 
-		udfDebug 0 "try lock from $s"
+    udfDebug 0 "try lock from $s"
 
-		## TODO check fo
-		(( ${#_bashlyk_afoClean[$BASHPID]} > 0 )) && rm -f ${_bashlyk_afoClean[$BASHPID]}
-		exec env _kurenma_flock="$$" flock -x -w 99 $fnLock $0 $s $$
+    ## TODO check fo
+    (( ${#_bashlyk_afoClean[$BASHPID]} > 0 )) && rm -f ${_bashlyk_afoClean[$BASHPID]}
+    exec env _kurenma_flock="$$" flock -x -w 99 $fnLock $0 $s $$
 
-	fi
+  fi
 
-	if [[ "$_kurenma_flock" != "$2" ]]; then
+  if [[ "$_kurenma_flock" != "$2" ]]; then
 
-		eval $( udfOnError retecho iErrorNotPermitted "invalid process $2" )
+    eval $( udfOnError retecho iErrorNotPermitted "invalid process $2" )
 
-	fi
+  fi
 
-	udfDebug 0 "starting from $s $2"
-	echo "${s}:$(date +%s)" >> $fnKnock
+  udfDebug 0 "starting from $s $2"
+  echo "${s}:$(date +%s)" >> $fnKnock
 
-	pathIni=$( _ pathIni )
+  pathIni=$( _ pathIni )
 
-	for s in $pathDat $patIni; do
+  for s in $pathDat $patIni; do
 
-		[[ -n "$s" && -d "$s" ]] || eval $( udfOnError NoSuchFileOrDir "$s" )
+    [[ -n "$s" && -d "$s" ]] || eval $( udfOnError NoSuchFileOrDir "$s" )
 
-	done
+  done
 
-	cnf="/etc/firehol/firehol.conf"
-	ini="${pathIni}/ipslist.ini"
+  cnf="/etc/firehol/firehol.conf"
+  ini="${pathIni}/ipslist.ini"
 
-	udfIni $ini "ipv4White:= ipv4Black:="
+  udfIni $ini "ipv4White:= ipv4Black:="
 
-	udfDebug 2 && udfShowVariable ipv4White ipv4Black ipv4Client
+  udfDebug 2 && udfShowVariable ipv4White ipv4Black ipv4Client
 
-	cp $cnf ${cnf:0:-3}bak
+  cp $cnf ${cnf:0:-3}bak
 
-	ipv4Client=$( wg show | grep 'endpoint:' | sed -r -e "s/^.*t: (.*):.*$/\1/" | sort | uniq | xargs )
+  ipv4Client=$( wg show | grep 'endpoint:' | sed -r -e "s/^.*t: (.*):.*$/\1/" | sort | uniq | xargs )
 
-	touch $fnKnock
-	udfMakeTemp fn
+  touch $fnKnock
+  udfMakeTemp fn
 
-	while read s; do
+  while read s; do
 
-		udfIsNumber ${s##*:} || continue
-		#
-		# 240 - time interval for safety from collisions
-		#
-		if (( $(date +%s) - ${s##*:} < 240 )); then
+    udfIsNumber ${s##*:} || continue
+    #
+    # 240 - time interval for safety from collisions
+    #
+    if (( $(date +%s) - ${s##*:} < 240 )); then
 
-			echo "$s"
-			ipv4Client+=" ${s%%:*}"
+      echo "$s"
+      ipv4Client+=" ${s%%:*}"
 
-		fi
+    fi
 
-	done < $fnKnock > $fn
-	mv -f $fn $fnKnock
+  done < $fnKnock > $fn
+  mv -f $fn $fnKnock
 
-	if udfIsValidVariable ipv4White; then
+  if udfIsValidVariable ipv4White; then
 
-		s="ipv4White=\"$( udfGetValidIPsOnly ${ipv4White//[,;]/ } ${1//[,;]/ } $ipv4Client )\""
-		[[ -z $ipv4White ]] && ipv4White='127.0.0.1'
-		udfDebug 2 "new white list $s"
-		sed -i -re "s/ipv4White=.*/$s/" $cnf
+    s="ipv4White=\"$( udfGetValidIPsOnly ${ipv4White//[,;]/ } ${1//[,;]/ } $ipv4Client )\""
+    [[ -z $ipv4White ]] && ipv4White='127.0.0.1'
+    udfDebug 2 "new white list $s"
+    sed -i -re "s/ipv4White=.*/$s/" $cnf
 
-	fi
+  fi
 
-	if udfIsValidVariable ipv4Black; then
+  if udfIsValidVariable ipv4Black; then
 
-		s="ipv4Black=\"$( udfGetValidIPsOnly ${ipv4Black//[,;]/ } ${2//[,;]/ } )\""
-		[[ -z $ipv4Black ]] && ipv4Black='1.1.1.1'
-		udfDebug 2 "new black list $s"
-		sed -i -re "s/ipv4Black=.*/$s/" $cnf
+    s="ipv4Black=\"$( udfGetValidIPsOnly ${ipv4Black//[,;]/ } ${2//[,;]/ } )\""
+    [[ -z $ipv4Black ]] && ipv4Black='1.1.1.1'
+    udfDebug 2 "new black list $s"
+    sed -i -re "s/ipv4Black=.*/$s/" $cnf
 
-	fi
+  fi
 
-	printf -- "\n\n\n---> the differences (if any) --->\n"
-	diff -du ${cnf:0:-3}bak $cnf
-	printf -- "\n<--- ------------------------ <---\n\n\n"
+  printf -- "\n\n\n---> the differences (if any) --->\n"
+  diff -du ${cnf:0:-3}bak $cnf
+  printf -- "\n<--- ------------------------ <---\n\n\n"
 
-	echo "Firehol configuration testing:"
-	if firehol debug 2>&1 | grep -A5 "ERROR\|FAILED"; then
+  echo "Firehol configuration testing:"
+  if firehol debug 2>&1 | grep -A5 "ERROR\|FAILED"; then
 
-		echo "restore old configuration:"
-		mv -v ${cnf:0:-3}bak $cnf
+    echo "restore old configuration:"
+    mv -v ${cnf:0:-3}bak $cnf
 
-		eval $( udfOnError throw InvalidArgument "$* and/or $ini" )
+    eval $( udfOnError throw InvalidArgument "$* and/or $ini" )
 
-	else
+  else
 
-		echo " OK!"
-		echo "Starting new configuration:"
+    echo " OK!"
+    echo "Starting new configuration:"
 
-		if echo commit | firehol try; then
+    if echo commit | firehol try; then
 
-			[[ -n "$*" ]] && kurenmactl start
+      [[ -n "$*" ]] && kurenmactl start
 
-			echo " OK."
+      echo " OK."
 
-		else
+    else
 
-			echo " FAILED.."
+      echo " FAILED.."
 
-		fi
+    fi
 
-	fi
+  fi
 
-	udfFinally "service down"
+  udfFinally "service down"
 
 }
 #
