kurenmac - improved logging for down by signal
kurenmac:
- added new Error state - NotAvailable
- improved messages for down by signal
- udfWatchdog:
  * remove udfUptime
  * return iErrorAbortedBySignal on stop signal

diff --git a/src/kurenmac b/src/kurenmac
--- a/src/kurenmac
+++ b/src/kurenmac
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Id: kurenmac 58 2016-09-08 22:43:04+04:00 toor $
+# $Id: kurenmac 59 2016-09-09 16:14:18+04:00 toor $
 #
 _kurenmac_sVersion=0.3
 #
@@ -9,6 +9,10 @@ _bashlyk=kurenma . bashlyk
 #
 #
 _peIPv4='\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
+_bashlyk_iErrorTimeExpired=167
+_bashlyk_hError[$_bashlyk_iErrorTimeExpired]="time expired"
+_bashlyk_iErrorNotAvailable=166
+_bashlyk_hError[$_bashlyk_iErrorNotAvailable]="target is not available"
 #
 #
 #
@@ -25,8 +29,7 @@ udfWatchdog() {
 
 		if [[ -s $1 && $( tail -n 1 $1 ) == "stop" ]]; then
 
-			i=1
-			udfUptime "service uptime"
+			i=$(_ iErrorAbortedBySignal)
 			break
 
 		fi
@@ -151,7 +154,12 @@ udfKnocking() {
 
 		fi
 
-		udfWatchdog $fnCtl 1 || exit 0
+		if ! udfWatchdog $fnCtl 1; then
+
+			echo "x"
+			return $(_ iErrorAbortedBySignal)
+
+		fi
 
 		nc -w 3 -z ${host} ${portAuth} 2>/dev/null && break
 		udfDebug 2 && echo -n "."
@@ -162,8 +170,8 @@ udfKnocking() {
 
 		if (( $i <= 0 )); then
 
-			echo "fail after 256 attempts"
-			eval $( udfOnError2 warn NotPermitted "${host}:${portAuth} are unreacheable" )
+			echo "fail after 256 attempts.. try again"
+			eval $( udfOnError2 warn NotAvailable "${host}:${portAuth}" )
 			i=256
 
 		fi
@@ -180,13 +188,19 @@ udfGetTunnelSettings() {
 
 	local fnPub fnAns sKey s
 
+	s="$(_ iErrorAbortedBySignal) stop signal received"
+
 	udfMakeTemp fnPub
 	udfMakeTemp fnAns
 
 	while true; do
 
-		udfKnocking && udfDebug 2 "ok."
-		udfWatchdog $fnCtl 4 || return 2
+		udfKnocking || break
+
+		udfDebug 2 "ok."
+
+		udfWatchdog $fnCtl 4 || break
+
 		sKey=$( wg genkey )
 
 		s="$( echo $sKey | wg pubkey | tee $fnPub | udfEcho - $cnClient | openssl smime -encrypt -aes256 -outform PEM $fnServerCrt | nc -w 24 -i 4 $host $portAuth | tee $fnAns | openssl smime -decrypt -inform PEM -inkey $fnClientKey | tr -d '\r' )"
@@ -201,7 +215,8 @@ udfGetTunnelSettings() {
 
 		eval $( udfOnError2 warn iErrorNotValidArgument "malformed answer from ${host}:${portAuth} $s" )
 
-		udfWatchdog $fnCtl 8 || return 2
+		s="$(_ iErrorAbortedBySignal ) stop signal received"
+		udfWatchdog $fnCtl 8 || break
 
 	done >&2
 
@@ -217,6 +232,9 @@ udfSetupTunnel() {
 	udfThrowOnEmptyVariable dev host
 
 	local ipClient ipServer peer port sKey
+
+	[[ $1 == $( _ iErrorAbortedBySignal  ) ]] && return $( _ iErrorAbortedBySignal  )
+	[[ $1 != "OK"   ]] && return $( _ iErrorNonValidArgument )
 
 	shift
 
@@ -316,7 +334,7 @@ udfMain() {
 	local csvSectionMain csvSectionSSL ipsAllowed
 
 	#
-	aId=( $( grep -Po '\044Id\072 \S+ \d+ \S+ \S+ \S+ \044' $0 ) ) && udfDebug 1 "$( _ s0 ) (с) ${aId[3]}, rev${aId[2]}"
+	aId=( $( grep -Po '\044Id\072 \S+ \d+ \S+ \S+ \S+ \044' $0 ) ) && udfDebug 1 "start $( _ s0 ) (с) ${aId[3]}, rev${aId[2]}"
 	#
 	fmtSSL="SSL auth info:\nClient Common Name - %s\nServer Common Name - %s\n"
 	fmtCon="Connection properties from %s:\nremote port: %d\nserver  key: %s\ntunnel  IPs: leased/remote - %s/%s\n"
@@ -382,7 +400,13 @@ udfMain() {
 		if $bStart; then
 
 			## TODO try first use saved wg config
-			udfSetupTunnel $( udfGetTunnelSettings )
+
+			udfSetupTunnel $( udfGetTunnelSettings ) || {
+
+				eval $( udfOnError2 warn $? "setup tunnel settings" )
+				break
+			}
+
 			$bDefaultRoute && udfSetDefaultRoute
 			udfDebug 1 && printf -- "\nclient configuration done.\n"
 			udfDebug 5 && udfShowPeerInfo
@@ -424,6 +448,8 @@ udfMain() {
 		done
 
 	done
+
+	udfFinally "service down after"
 
 }
 #
