agreements of version bashlyk 1.92.821 are used

diff --git a/src/update-firehol b/src/update-firehol
--- a/src/update-firehol
+++ b/src/update-firehol
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #
-# $Id: update-firehol 197 2018-03-31 15:11:06+04:00 toor $
+# $Id: update-firehol 201 2018-04-10 18:33:38+04:00 toor $
 #
 #
 _bashlyk=kurenma . bashlyk
@@ -41,7 +41,8 @@ _bashlyk_hError[$_bashlyk_iErrorTimeExpired]="time expired"
 kurenma-update-firehol::main() {
 
 
-  [[ $UID == 0 ]] || on error warn+exit NotPermitted "You must be root to run this."
+  [[ $UID == 0 ]] || \
+    error NotPermitted warn+exit "You must be root to run this."
 
   pid::onStarted.exit
 
@@ -55,13 +56,13 @@ kurenma-update-firehol::main() {
   pathDat=$( _ pathDat )
   fnKnock="${pathDat}/lastknocks.dat"
   fnLock="$( _ pathRun )/$( _ s0 ).lock"
-  mkdir -p $pathDat || on error throw NotExistNotCreated $pathDat
-  touch $fnLock     || on error throw NotExistNotCreated $fnLock
+  mkdir -p $pathDat || error NotExistNotCreated throw $pathDat
+  touch $fnLock     || error NotExistNotCreated throw $fnLock
 
   eval set -- $( _ sArg )
 
-  s=$( net::ipv4.host $1 ) || on error echo+exit InvalidArgument               \
-                                 "${1:-first argument}: IP or hostname required"
+  s=$( net::ipv4.host $1 ) || \
+    error InvalidArgument echo+exit "${1:-first argument}: IP or hostname required"
 
   if [[ ! $_kurenma_flock ]]; then
 
@@ -77,7 +78,7 @@ kurenma-update-firehol::main() {
 
   if [[ ! $2 || $2 != $_kurenma_flock ]]; then
 
-    on error echo+return NotPermitted "unexpected call of the this command"
+    error NotPermitted echo+return "unexpected call of the this command"
 
   fi
 
@@ -175,7 +176,7 @@ kurenma-update-firehol::main() {
     echo "restore old configuration:"
     mv -v ${cnf:0:-3}bak $cnf
 
-    on error warn+exit InvalidArgument "$* and/or $ini"
+    error InvalidArgument warn+exit "$* and/or $ini"
 
   else
 
